Se agrega funcionamiento del hover en ciudades
labexp/lascallesdelasmujeres pull request #9
Opened 2018-09-08 01:14 UTC by tammypmc

2018-09-13 00:43 UTC, jamescr requested changes
Ahora los nombres de las ciudades no aparecen ordenadas alfabéticamente. Creo que sería bueno arreglar esto antes de aceptar el PR.

2018-09-14 22:32 UTC, samanda22 commented
Arreglé el orden alfabético de las ciudades, hice el pull request al repositorio de @tammypmc

2018-09-20 15:47 UTC, betCG approved these changes

2018-09-20 15:47 UTC, merged

2018-09-20 16:37 UTC, tammypmc commented
Este PR soluciona los cambios propuestos en #2